project: 
  type: website
  output-dir: docs
  render:
    - "*.*"
    - "!tutorials/python-notebooks/*.ipynb"
    - "!tutorials/r/gdalcubes.qmd"
    - "!tutorials/r/5-r-geospatial.qmd"

execute:
  freeze: auto
  
website:
  page-navigation: true  
  title: "2024 Quarto Workshop"
  favicon: "images/favicon-16x16.png"
  site-url: https://nmfs-opensci.github.io/Quarto-Workshop-2024
  repo-url: https://github.com/nmfs-opensci/Quarto-Workshop-2024
  repo-actions: [edit, issue, source]
  
  page-footer: <img src="https://github.com/nmfs-opensci/assets/blob/main/logo/nmfs-opensci-logo2.png?raw=true" alt="NMFS Open Science logo" style="width:150px"><br />NMFS Open Science (2023)
 
  sidebar:
    logo: https://github.com/nmfs-opensci/assets/blob/main/logo/nmfs-opensci-logo2.png?raw=true
    pinned: true
    align: center
    
    style: "docked"
    collapse-level: 1
    toc-expand: false
    contents:
      - section: "Welcome"
        href: index.qmd
        contents:
          - team.md
          - schedule.md
          - section: Set-up
            contents:
            - set-up.qmd
            - text: R and RStudio on your computer
              href: content/02-local-setup-r.qmd
            - text: R and RStudion on the JupyterHub
              href: content/02-jupyterhub-setup-r.qmd
            - text: Git-Authentication
              href: content/02-git.md
            - text: Git-JupyterLab
              href: content/02-git-jupyter.md
            - text: Git-RStudio
              href: content/02-git-rstudio.md
          - coc.md
      - section: "Orientation"
        contents:
        - text: Reproducible Reports
          href: content/01-repro-reports.qmd
        - text: Intro to RStudio
          href: content/02-rstudio.qmd
        - text: JupyterHubs
          href: content/01-intro-to-jupyterhub.qmd
      - section: "Tutorials"
        contents:
        - text: Coming!
      - text: <img width=100px>
      - text: <img src="/images/noaa_emblem_logo-2022.png" width=100px>
        href: https://fisheries.noaa.gov
  navbar:
    background: primary
    search: true
    right: 
      - icon: server
        href: https://nmfs-openscapes.2i2c.cloud/
        text: "JupyterHub"
      - icon: wechat
        href: https://github.com/nmfs-opensci/Quarto-Workshop-2024/discussions
        text: "Discussions"
      - icon: github
        href: https://github.com/nmfs-opensci/Quarto-Workshop-2024
        text: "Repo"
      - icon: globe
        href: https://github.com/nmfs-opensci
        text: "GH org"


format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true
    toc-depth: 2
    include-before-body: translate.html

filters:
  - include-files.lua
  - quarto
